Update WebSocketClient.swift
vapor/websocket-kit pull request #99
Opened 2021-08-16 23:44 UTC by axtonpitt

Fix `TLSConfiguration.forClient()` deprecation warning

```
warning: 'forClient(cipherSuites:minimumTLSVersion:maximumTLSVersion:certificateVerification:trustRoots:certificateChain:privateKey:applicationProtocols:shutdownTimeout:keyLogCallback:)' is deprecated: renamed to 'makeClientConfiguration()'
```

2021-08-18 08:13 UTC, 0xTim commented
@axtonpitt  thanks for this! Can you bump the NIOSSL to `.package(url: "https://github.com/apple/swift-nio-ssl.git", from: "2.14.0"),` in Package.swift?

2021-08-18 08:13 UTC, 0xTim requested changes
Need to bump the manifest as well

2021-08-18 08:18 UTC, axtonpitt commented
@0xTim Cool done. I didn't understand what did you meant by "manifest" though?

2021-08-18 08:20 UTC, 0xTim commented
Sorry manifest == Package.swift!

2021-08-18 08:20 UTC, 0xTim approved these changes

2021-08-18 15:30 UTC, 0xTim commented
@axtonpitt I've fixed all the tests, can you update your branch so we can get CI green?

2021-08-18 22:28 UTC, axtonpitt commented
@0xTim done

2021-08-19 00:06 UTC, 0xTim approved these changes

2021-08-19 09:07 UTC, merged